apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeislands.engine.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeislands.labels" . | nindent 4 }}
    app.kubernetes.io/component: engine
spec:
  type: {{ .Values.engine.service.type }}
  ports:
    - port: {{ .Values.engine.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    app.kubernetes.io/name: {{ include "kubeislands.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: engine
